---
#
# Installing Filebeat
#

# Install Filebeat 
- name: Set filebeat repo
  shell:
    cmd: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.5.1-x86_64.rpm

- name: Install Filebeat rpms
  shell:
    cmd: rpm -vi filebeat-7.5.1-x86_64.rpm
  ignore_errors: true

- name: Copy filebeat config
  copy:
    src=filebeat.yml
    dest=/etc/filebeat/filebeat.yml
    owner=root
    group=root
    mode=0644
  become: true

# Starting Filebeat

- name: Setup Filebeat service
  service: name=filebeat state=started enabled=true
  become: true
