---
#
# Installing Logstash
#

# Install Logstash

- name: Install Logstash rpms
  yum:
    name: logstash
  become: true

- name: Copy logstash config file INPUT
  copy:
    src=input.conf
    dest=/etc/logstash/conf.d/
    owner=root
    group=root
    mode=0644
  become: true

- name: Copy logstash config file OUTPUT
  copy:
    src=output.conf
    dest=/etc/logstash/conf.d/
    owner=root
    group=root
    mode=0644
  become: true

- name: Copy logstash config file FILTER
  copy:
    src=filter.conf
    dest=/etc/logstash/conf.d/
    owner=root
    group=root
    mode=0644
  become: true

- name: Setup logstash service
  service: name=logstash state=started enabled=true
  become: true
